/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package JNILib;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    static {
        System.loadLibrary("native");
    }

    public native void sayHello();
}
