/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNILib_Library */

#ifndef _Included_JNILib_Library
#define _Included_JNILib_Library
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNILib_Library
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNILib_Library_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
